# Generated by Django 3.0.7 on 2020-07-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methycaptureinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '甲基化捕获文库信息表'},
        ),
        migrations.AlterModelOptions(
            name='methylibraryinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '甲基化建库表'},
        ),
        migrations.AlterModelOptions(
            name='methypoolinginfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '甲基化pooling表'},
        ),
    ]
