# Generated by Django 3.0.7 on 2020-07-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS', '0002_auto_20200701_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methycaptureinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_MethyCaptureInfo', 'Can bulk delete data'), ('bulk_update_MethyCaptureInfo', 'Can bulk update data')], 'verbose_name': '甲基化捕获文库信息表'},
        ),
        migrations.AlterModelOptions(
            name='methylibraryinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_MethyLibraryInfo', 'Can bulk delete data'), ('bulk_update_MethyLibraryInfo', 'Can bulk update data')], 'verbose_name': '甲基化建库表'},
        ),
        migrations.AlterModelOptions(
            name='methypoolinginfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_MethyPoolingInfo', 'Can bulk delete data'), ('bulk_update_MethyPoolingInfo', 'Can bulk update data')], 'verbose_name': '甲基化pooling表'},
        ),
    ]
