# Generated by Django 3.0.7 on 2020-07-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS', '0003_auto_20200702_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methycaptureinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_MethyCaptureInfo', 'Can bulk delete 甲基化捕获文库信息表'), ('bulk_update_MethyCaptureInfo', 'Can bulk update 甲基化捕获文库信息表')], 'verbose_name': '甲基化捕获文库信息表'},
        ),
        migrations.AlterModelOptions(
            name='methylibraryinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_MethyLibraryInfo', 'Can bulk delete 甲基化建库表'), ('bulk_update_MethyLibraryInfo', 'Can bulk update 甲基化建库表')], 'verbose_name': '甲基化建库表'},
        ),
        migrations.AlterModelOptions(
            name='methypoolinginfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_MethyPoolingInfo', 'Can bulk delete 甲基化pooling表'), ('bulk_update_MethyPoolingInfo', 'Can bulk update 甲基化pooling表')], 'verbose_name': '甲基化pooling表'},
        ),
    ]
