# Generated by Django 2.1.7 on 2020-06-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BIS', '0001_initial'),
        ('LIMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethyQCInfo',
            fields=[
                ('QC_id', models.CharField(blank=True, db_column='Sample', max_length=35, null=True, unique=True)),
                ('data_size_gb_field', models.FloatField(blank=True, db_column='Data_Size-Gb', null=True)),
                ('clean_rate_field', models.FloatField(blank=True, db_column='Clean_Rate', null=True)),
                ('r1_q20', models.FloatField(blank=True, db_column='R1_Q20', null=True)),
                ('r2_q20', models.FloatField(blank=True, db_column='R2_Q20', null=True)),
                ('r1_q30', models.FloatField(blank=True, db_column='R1_Q30', null=True)),
                ('r2_q30', models.FloatField(blank=True, db_column='R2_Q30', null=True)),
                ('gc_content', models.FloatField(blank=True, db_column='GC_Content', null=True)),
                ('bs_conversion_rate_lambda_dna_field', models.FloatField(blank=True, db_column='BS_conversion_rate-lambda_DNA', null=True)),
                ('bs_conversion_rate_chh_field', models.FloatField(blank=True, db_column='BS_conversion_rate-CHH', null=True)),
                ('bs_conversion_rate_chg_field', models.FloatField(blank=True, db_column='BS_conversion_rate-CHG', null=True)),
                ('uniquely_paired_mapping_rate', models.FloatField(blank=True, db_column='Uniquely_Paired_Mapping_Rate', null=True)),
                ('mismatch_and_indel_rate', models.FloatField(blank=True, db_column='Mismatch_and_InDel_Rate', null=True)),
                ('mode_fragment_length_bp_field', models.FloatField(blank=True, db_column='Mode_Fragment_Length-bp', null=True)),
                ('genome_duplication_rate', models.FloatField(blank=True, db_column='Genome_Duplication_Rate', null=True)),
                ('genome_depth_x_field', models.FloatField(blank=True, db_column='Genome_Depth', null=True)),
                ('genome_dedupped_depth_x_field', models.FloatField(blank=True, db_column='Genome_Dedupped_Depth', null=True)),
                ('genome_coverage', models.FloatField(blank=True, db_column='Genome_Coverage', null=True)),
                ('genome_4x_cpg_depth_x_field', models.FloatField(blank=True, db_column='Genome_4X_CpG_Depth', null=True)),
                ('genome_4x_cpg_coverage', models.FloatField(blank=True, db_column='Genome_4X_CpG_Coverage', null=True)),
                ('genome_4x_cpg_methylation_level', models.FloatField(blank=True, db_column='Genome_4X_CpG_methylation_level', null=True)),
                ('panel_4x_cpg_depth_x_field', models.FloatField(blank=True, db_column='Panel_4X_CpG_Depth', null=True)),
                ('panel_4x_cpg_coverage', models.FloatField(blank=True, db_column='Panel_4X_CpG_Coverage', null=True)),
                ('panel_4x_cpg_methylation_level', models.FloatField(blank=True, db_column='Panel_4X_CpG_methylation_level', null=True)),
                ('panel_ontarget_rate_region_field', models.FloatField(blank=True, db_column='Panel_Ontarget_Rate-region', null=True)),
                ('panel_duplication_rate_region_field', models.FloatField(blank=True, db_column='Panel_Duplication_Rate-region', null=True)),
                ('panel_depth_site_x_field', models.FloatField(blank=True, db_column='Panel_Depth-site_X', null=True)),
                ('panel_dedupped_depth_site_x_field', models.FloatField(blank=True, db_column='Panel_Dedupped_Depth-site_X', null=True)),
                ('panel_coverage_site_1x_field', models.FloatField(blank=True, db_column='Panel_Coverage-site_1X', null=True)),
                ('panel_coverage_site_10x_field', models.FloatField(blank=True, db_column='Panel_Coverage-site_10X', null=True)),
                ('panel_coverage_site_20x_field', models.FloatField(blank=True, db_column='Panel_Coverage-site_20X', null=True)),
                ('panel_coverage_site_50x_field', models.FloatField(blank=True, db_column='Panel_Coverage-site_50X', null=True)),
                ('panel_coverage_site_100x_field', models.FloatField(blank=True, db_column='Panel_Coverage-site_100X', null=True)),
                ('panel_uniformity_site_20_mean_field', models.FloatField(blank=True, db_column='Panel_Uniformity-site_gt0.2mean', null=True)),
                ('strand_balance_f_field', models.FloatField(blank=True, db_column='Strand_balance-F', null=True)),
                ('strand_balance_r_field', models.FloatField(blank=True, db_column='Strand_balance-R', null=True)),
                ('gc_bin_depth_ratio', models.FloatField(blank=True, db_column='GC_bin_depth_ratio', null=True)),
                ('memo', models.TextField(blank=True, db_column='备注', null=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, db_column='最近修改时间')),
                ('dna_id', models.ForeignKey(blank=True, db_column='核酸提取编号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MethyQCInfo_BIS2ExtractInfo', to='BIS.ExtractInfo', to_field='dna_id')),
                ('poolingLB_id', models.ForeignKey(blank=True, db_column='捕获文库名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MethyQCInfo_LIMS2MethyCaptureInfo', to='LIMS.MethyCaptureInfo', to_field='poolingLB_id')),
                ('sample_id', models.ForeignKey(blank=True, db_column='样本编号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MethyQCInfo_BIS2SampleInfo', to='BIS.SampleInfo', to_field='sample_id')),
                ('sampler_id', models.ForeignKey(blank=True, db_column='患者编号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MethyQCInfo_BIS2SampleInventoryInfo', to='BIS.SampleInventoryInfo', to_field='sampler_id')),
            ],
            options={
                'verbose_name': '样本甲基化检测测序质控表',
                'db_table': '样本甲基化检测测序质控表',
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='SequencingInfo',
            fields=[
                ('sequencing_id', models.CharField(blank=True, db_column='上机文库号', max_length=35, null=True, unique=True)),
                ('send_date', models.DateField(blank=True, db_column='送测日期', null=True)),
                ('start_time', models.DateField(blank=True, db_column='上机时间', null=True)),
                ('end_time', models.DateField(blank=True, db_column='下机时间', null=True)),
                ('machine_id', models.CharField(blank=True, db_column='机器号', max_length=100, null=True)),
                ('chip_id', models.CharField(blank=True, db_column='芯片号', max_length=100, null=True)),
                ('memo', models.TextField(blank=True, db_column='备注', null=True)),
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, db_column='最近修改时间')),
                ('poolingLB_id', models.ManyToManyField(blank=True, db_column='捕获文库名', related_name='SequencingInfo_LIMS2MethyCaptureInfo', to='LIMS.MethyCaptureInfo')),
            ],
            options={
                'verbose_name': '测序登记表',
                'db_table': '测序登记表',
                'ordering': ['-index'],
            },
        ),
        migrations.AddField(
            model_name='methyqcinfo',
            name='sequencing_id',
            field=models.ForeignKey(blank=True, db_column='上机文库号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MethyQCInfo_SequencingInfo', to='SEQ.SequencingInfo', to_field='sequencing_id'),
        ),
        migrations.AddField(
            model_name='methyqcinfo',
            name='singleLB_Pooling_id',
            field=models.ForeignKey(blank=True, db_column='测序文库名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MethyQCInfo_LIMS2MethyPoolingInfo', to='LIMS.MethyPoolingInfo', to_field='singleLB_Pooling_id'),
        ),
        migrations.AddField(
            model_name='methyqcinfo',
            name='singleLB_id',
            field=models.ForeignKey(blank=True, db_column='建库编号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MethyQCInfo_LIMS2MethyLibraryInfo', to='LIMS.MethyLibraryInfo', to_field='singleLB_id'),
        ),
    ]
