# Generated by Django 3.0.7 on 2020-07-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methyqcinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '样本甲基化检测测序质控表'},
        ),
        migrations.AlterModelOptions(
            name='sequencinginfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '测序登记表'},
        ),
    ]
