# Generated by Django 3.0.7 on 2020-07-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEQ', '0002_auto_20200701_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methyqcinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SequencingInfo', 'Can bulk delete data'), ('bulk_update_SequencingInfo', 'Can bulk update data')], 'verbose_name': '样本甲基化检测测序质控表'},
        ),
        migrations.AlterModelOptions(
            name='sequencinginfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SequencingInfo', 'Can bulk delete data'), ('bulk_update_SequencingInfo', 'Can bulk update data')], 'verbose_name': '测序登记表'},
        ),
    ]
