# Generated by Django 3.0.7 on 2020-07-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEQ', '0003_auto_20200702_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methyqcinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SequencingInfo', 'Can bulk delete 样本甲基化检测测序质控表'), ('bulk_update_SequencingInfo', 'Can bulk update 样本甲基化检测测序质控表')], 'verbose_name': '样本甲基化检测测序质控表'},
        ),
        migrations.AlterModelOptions(
            name='sequencinginfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SequencingInfo', 'Can bulk delete 测序登记表'), ('bulk_update_SequencingInfo', 'Can bulk update 测序登记表')], 'verbose_name': '测序登记表'},
        ),
    ]
