# Generated by Django 3.0.7 on 2020-07-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnausagerecordinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '样本核酸使用记录表'},
        ),
        migrations.AlterModelOptions(
            name='extractinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '样本提取表'},
        ),
        migrations.AlterModelOptions(
            name='sampleinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '样本信息表'},
        ),
        migrations.AlterModelOptions(
            name='sampleinventoryinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '样本库存信息表'},
        ),
    ]
