# Generated by Django 3.0.7 on 2020-08-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BIS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractinfo',
            name='sampleinfo',
        ),
    ]
