# Generated by Django 3.0.7 on 2020-07-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BIS', '0002_auto_20200701_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnausagerecordinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_DNAUsageRecordInfo', 'Can bulk delete data'), ('bulk_update_DNAUsageRecordInfo', 'Can bulk update data')], 'verbose_name': '样本核酸使用记录表'},
        ),
        migrations.AlterModelOptions(
            name='extractinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_ExtractInfo', 'Can bulk delete data'), ('bulk_update_ExtractInfo', 'Can bulk update data')], 'verbose_name': '样本提取表'},
        ),
        migrations.AlterModelOptions(
            name='sampleinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SampleInfo', 'Can bulk delete data'), ('bulk_update_SampleInfo', 'Can bulk update data')], 'verbose_name': '样本信息表'},
        ),
        migrations.AlterModelOptions(
            name='sampleinventoryinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SampleInventoryInfo', 'Can bulk delete data'), ('bulk_update_SampleInventoryInfo', 'Can bulk update data')], 'verbose_name': '样本库存信息表'},
        ),
    ]
