# Generated by Django 3.0.7 on 2020-07-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BIS', '0003_auto_20200702_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dnausagerecordinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_DNAUsageRecordInfo', 'Can bulk delete 样本核酸使用记录表'), ('bulk_update_DNAUsageRecordInfo', 'Can bulk update 样本核酸使用记录表')], 'verbose_name': '样本核酸使用记录表'},
        ),
        migrations.AlterModelOptions(
            name='extractinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_ExtractInfo', 'Can bulk delete 样本提取表'), ('bulk_update_ExtractInfo', 'Can bulk update 样本提取表')], 'verbose_name': '样本提取表'},
        ),
        migrations.AlterModelOptions(
            name='sampleinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SampleInfo', 'Can bulk delete 样本信息表'), ('bulk_update_SampleInfo', 'Can bulk update 样本信息表')], 'verbose_name': '样本信息表'},
        ),
        migrations.AlterModelOptions(
            name='sampleinventoryinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_SampleInventoryInfo', 'Can bulk delete 样本库存信息表'), ('bulk_update_SampleInventoryInfo', 'Can bulk update 样本库存信息表')], 'verbose_name': '样本库存信息表'},
        ),
    ]
