# Generated by Django 3.0.7 on 2020-07-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '基本临床信息表'},
        ),
        migrations.AlterModelOptions(
            name='followupinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '随访信息表'},
        ),
        migrations.AlterModelOptions(
            name='liverbiocheminfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '肝癌生化检测结果信息表'},
        ),
        migrations.AlterModelOptions(
            name='liverpathologicalinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '肝癌病理报告信息表'},
        ),
        migrations.AlterModelOptions(
            name='livertmdinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete', 'Can bulk delete data'), ('bulk_update', 'Can bulk update data')], 'verbose_name': '肝癌肿瘤标志物检测结果信息表'},
        ),
    ]
