# Generated by Django 3.0.7 on 2020-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinfo',
            name='clinical_id',
            field=models.CharField(blank=True, db_column='病历编号', max_length=80, null=True, unique=True),
        ),
    ]
