# Generated by Django 3.0.7 on 2020-07-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMR', '0003_auto_20200702_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_ClinicalInfo', 'Can bulk delete 基本临床信息表'), ('bulk_update_ClinicalInfo', 'Can bulk update 基本临床信息表')], 'verbose_name': '基本临床信息表'},
        ),
        migrations.AlterModelOptions(
            name='followupinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_FollowupInfo', 'Can bulk delete 随访信息表'), ('bulk_update_FollowupInfo', 'Can bulk update 随访信息表')], 'verbose_name': '随访信息表'},
        ),
        migrations.AlterModelOptions(
            name='liverbiocheminfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_LiverBiochemInfo', 'Can bulk delete 肝癌生化检测结果信息表'), ('bulk_update_LiverBiochemInfo', 'Can bulk update 肝癌生化检测结果信息表')], 'verbose_name': '肝癌生化检测结果信息表'},
        ),
        migrations.AlterModelOptions(
            name='liverpathologicalinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_LiverPathologicalInfo', 'Can bulk delete 肝癌病理报告信息表'), ('bulk_update_LiverPathologicalInfo', 'Can bulk update 肝癌病理报告信息表')], 'verbose_name': '肝癌病理报告信息表'},
        ),
        migrations.AlterModelOptions(
            name='livertmdinfo',
            options={'ordering': ['-index'], 'permissions': [('bulk_delete_LiverTMDInfo', 'Can bulk delete 肝癌肿瘤标志物检测结果信息表'), ('bulk_update_LiverTMDInfo', 'Can bulk update 肝癌肿瘤标志物检测结果信息表')], 'verbose_name': '肝癌肿瘤标志物检测结果信息表'},
        ),
    ]
