# Generated by Django 3.0.7 on 2020-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMR', '0003_auto_20200812_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupinfo',
            name='death_bool',
            field=models.CharField(blank=True, db_column='死因是否与肿瘤相关', default='否', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='followupinfo',
            name='recur_bool',
            field=models.CharField(blank=True, db_column='是否复发', default='否', max_length=10, null=True),
        ),
    ]
