# Generated by Django 3.0.7 on 2020-08-12 03:50

from django.db import migrations, models

import ADVANCE.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.FileField(db_column='上传文件', null=True, upload_to=ADVANCE.models.user_directory_path)),
                ('uploadUrl', models.CharField(db_column='项目', max_length=35)),
                ('uploadOperator', models.CharField(blank=True, db_column='上传者', max_length=35, null=True)),
                ('uploadTime', models.DateTimeField(auto_now=True, db_column='上传时间')),
            ],
            options={
                'verbose_name': '上传文件信息表',
                'db_table': '上传文件信息表',
                'permissions': [('access_Advance', 'Can access 高级功能')],
            },
        ),
    ]
