# Generated by Django 2.1.7 on 2020-06-30 10:47

import ADVANCE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('uploadFile', models.FileField(db_column='上传文件', null=True, upload_to=ADVANCE.models.user_directory_path)),
                ('uploadUrl', models.CharField(db_column='项目', max_length=35)),
                ('uploadOperator', models.CharField(blank=True, db_column='上传者', max_length=35, null=True)),
                ('uploadTime', models.DateTimeField(auto_now=True, db_column='上传时间')),
                ('index', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '上传文件信息表',
                'db_table': '上传文件信息表',
            },
        ),
    ]
