# Generated by Django 3.0.7 on 2020-07-07 04:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nick_name', models.CharField(blank=True, db_column='昵称', error_messages={'nick_name_unique': '该昵称已被占用。'}, max_length=35, unique=True)),
                ('email', models.EmailField(db_column='邮箱', error_messages={'email_unique': '该邮箱地址已被占用。'}, max_length=254, unique=True)),
                ('avatar', imagekit.models.fields.ProcessedImageField(db_column='头像', default='avatar/default.jpg', upload_to='avatar')),
                ('role', models.SmallIntegerField(choices=[(1, '超级系统管理员'), (2, '项目管理员'), (3, '模块系统管理员'), (4, '普通用户')], db_column='角色', default=4)),
                ('memo', models.TextField(blank=True, db_column='备注', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='创建时间')),
                ('last_login_time', models.DateTimeField(blank=True, db_column='最近登录时间', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': 'users',
                'db_table': '用户信息表',
                'ordering': ['-create_time'],
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_changed', models.CharField(blank=True, db_column='被变更的模型', max_length=35, null=True)),
                ('operation', models.CharField(blank=True, db_column='操作', max_length=25, null=True)),
                ('memo', models.TextField(blank=True, db_column='备注', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='创建时间')),
                ('last_modify_time', models.DateTimeField(auto_now=True, db_column='最近修改时间')),
                ('userinfo', models.ForeignKey(blank=True, db_column='用户信息', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DatabaseRecord_UserInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '数据库增删改记录表',
                'db_table': '数据库增删改记录表',
                'ordering': ['-last_modify_time'],
            },
        ),
    ]
