# Generated by Django 3.0.7 on 2020-07-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_auto_20200701_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, db_column='头像', null=True, upload_to='avatar'),
        ),
    ]
