# Generated by Django 3.0.7 on 2020-07-01 12:20

import USER.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_auto_20200701_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, db_column='头像', null=True, upload_to=USER.models.user_directory_path),
        ),
    ]
