# Generated by Django 3.0.7 on 2020-07-02 01:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0005_auto_20200701_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(db_column='头像', default='avatar/default.jpg', upload_to='avatar'),
        ),
    ]
