# Generated by Django 3.0.7 on 2020-07-03 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_auto_20200702_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaserecord',
            name='nick_name',
        ),
        migrations.AddField(
            model_name='databaserecord',
            name='user_index',
            field=models.ForeignKey(blank=True, db_column='用户index', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DatabaseRecord_UserInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
